### ISSUE TITLE
Make it clear on how to create an new worktree without a remote branch (new branch)

### ISSUE THREAD

**Issue by Sov3rain** [philstainer/git-worktree#6]
Hey, as I understand it, for now when creating a new worktree without tracking an existing branch, you need to :
- Command Palette -> Worktree Add.
- Set a name for the worktree.
- When the prompt asks for a branch to track, press ESCAPE.
- Then you'll have a new worktree with a new branch to push on the origin.

This is somewhat confusing. I would prefer to have a top level option in the branch list like "create new branch". What's your opinion ?

**Comment by philstainer** [comment]
Yeah, exactly, but I normally select my `main` or `master` as my tracking branch

1. Command Palette -> 'Worktree Add'
2. Select 'Create new worktree'
3. Set a name for the worktree
4. Set your tracking branch
5. Done 🚀 

Just thinking about it, I get why it's confusing / feels overly complex, but I wanted to make it easier to create / add a worktree in one place

Example:

I have 2 branches, `main` and `my-feature`, `my-feature` is 2 commits behind main. 

I'm currently on `my-feature` worktree and I create a new worktree called `my-bug-fix`with your workflow above, you will end up creating a new worktree based on your `my-feature` branch (2 commits behind)

To bring this inline with `main` you would have set your tracking to `my-bug-fix` and then pull in changes from `main`

Now you may want this, but a lot of the time you may want to just switch and fix something

--

Couple of ways to improve this:

1. I could try to resolve your tracking branch automatically (What happens if you want to branch off a feature branch, so we would lose the flexibility) or maybe an setting?

2. Flow Change

  - Command Palette -> 'Worktree Add'
  - Select remote branch
  - Prompt for worktree name (defaulted to whatever you picked) but if you change the name it will create a new worktree based on the remote branch
  - Done 🚀 

3. Make separate commands for adding remote and creating new worktree (Going to be a little annoying imo)

4. Update the docs to make it easier for people to understand

**Comment by Sov3rain** [comment]
Thanks for explaining your reasoning, it makes a lot more sense now that I'm thinking about it. I was not particularly familiar with the term "tracking branch", (we are calling it "the base branch") so it all got mixed up in my head with the remote branch.

A more detailed explanation in the readme file should resolve the misunderstanding of what is (and what is not) the tracking branch.

**Comment by philstainer** [comment]
Yeah I guess you could think of it as the base branch as the tracking branch gets changed to the one you create when its pushed to the remote

I'll add an explanation to the add worktree command in the readme 👍

**Comment by Sov3rain** [comment]
I don't know what's possible or not with prompts from the command palette in VS Code, but I'll probably try to notify the user in some way that creating a worktree from another worktree is not advisable, but still let them go through.

**Comment by philstainer** [comment]
The more I think about it, the more it makes sense to abort the creation of a new worktree if you didn't select a tracking branch

1. I'll update the docs for the add worktree command
2. I'll sort the tracking branch's so that `main` or `master` is always the first branch

**Comment by Sov3rain** [comment]
Well, I've got a clearer picture in mind regarding new worktrees. When I want to develop a new feature in a new worktree, I expect it to create a new branch (which it does) based on another branch of my choice. What I expect next is that it would create a new remote branch, not setting the remote branch to the tracked branch I choosed beforehand.

See this example:
![image](https://user-images.githubusercontent.com/10755450/234581951-ff7f9376-46f4-4c30-a26a-4b261196b8b0.png)

Here, I would expect my local `refactor/database-layer` branch to have a new remote branch `origin/refactor/database-layer` that I need to push, not `origin/staging`.

What do you think?

**Comment by philstainer** [comment]
Great 👍 

Regarding your issue, do you have the setting `shouldPushBranchAutomatically` turned on? 

If not then that's more than likely your issue here, you can use the publish command to publish that branch later on when needed and that should correct your tracking branch

This is due to needing the created branch on remote before we set the tracking to origin/your-branch
